### ISSUE TITLE
requesting to assaign a task

### ISSUE THREAD

**Issue by LokeshYarramallu** [iSiddharth20/Chatbot-Using-OpenAI-API#4]
Is there anything that i can contribute into this repo your other repos are quiet interesting, in the way i came into this repo, i am beginner and want to contribute under hacktober fest so please let me know if you cn assaign me in this if possible

**Comment by iSiddharth20** [comment]
Hello Lokesh,
Thank You for reaching out to me. 
You can Fork this repository and make as many changes as you seem fit. I leave it to your imagination and skillset to fix any bugs you could find or improve on any existing functionality or even add new features to the project! 
Once you've finished working, send me a pull request with appropriate documentation noting down the specific changes and/or instructions and I'd be happy to review and merge those changes.
Good Luck with your Career and Hacktoberfest!
